services:
  - type: web
    name: coding-challenge-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://coding_challenge_platform_user:lMxyQpBH4d5hRZhVdlpktt23WUOaIYfJ@dpg-d3fvlah5pdvs73c092hg-a.oregon-postgres.render.com/coding_challenge_platform
      - key: PYTHON_VERSION
        value: 3.11.0
